#! /usr/bin/python
'''
 *  $Id: JobOpt_CalibrationPed_fromRoot, 2015-03-02 15:40:09 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
#-------------------------------------------------------------------
    NOTE:   input data is scientific root data(after Hex2Root)
'''

#-------------------------------------------------------------------
import os
import DMPSW                    # Load DAMPE software
import libDmpCalPed as DmpCalPed

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.SetEventNumber(4)     # default: -1
#DMPSW.Core.SetStartTime("2014-11-17 13:37:20")     # default: 2013-01-01 00:00:00
#DMPSW.Core.SetStopTime("2014-11-17 13:39:30")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off
DMPSW.Core.SetMode("EQM")

#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.InputPath(os.environ["DMPSWWORK"]+"/data/sci")
DMPSW.RootIOSvc.SetInputFile("./DmpRdcData.root")
#DMPSW.RootIOSvc.OutputFile("./DmpCalBgoMip.root")
#DMPSW.RootIOSvc.WriteList("Calibration/Bgo")  # split by ;
#DMPSW.RootIOSvc.OutputPath(os.environ["DMPSWWORK"]+"/run/data/cal/ped")

#-------------------------------------------------------------------
# Creat user's service or algorithm
calPed = DmpCalPed.DmpAlgCalibrationPed()
DMPSW.AlgMgr.Append(calPed)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

