#! /usr/bin/python
'''
 *  $Id: JobOpt_BgoPed_fromHex, 2014-11-09 15:09:29 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
#-------------------------------------------------------------------
    NOTE:   input data is scientific binary data
'''

#-------------------------------------------------------------------
import os
import glob
import DMPSW                    # Load DAMPE software
import libDmpHex2Root as Hex2Root
import libDmpBgoPed as DmpBgoPed

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.MaxEventNumber(4)     # default: -1
#DMPSW.Core.StartTime("2013-01-01 00:00:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.StopTime("2016-01-01 00:00:00")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off

DBase=DMPSW.WorkPath+"/run/BT"
#-------------------------------------------------------------------
# RootIOSvc options
DMPSW.RootIOSvc.InputPath(DBase+"/sci")
newestData=max(glob.iglob(DBase+"/sci/*.frd"),key=os.path.getctime)
DMPSW.RootIOSvc.InputFile(newestData)
#DMPSW.RootIOSvc.OutputPath(DMPSW.WorkPath+"/run/data/cal/ped")
DMPSW.RootIOSvc.WriteList("Calibration/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = Hex2Root.DmpAlgHex2Root()
calBgoPed = DmpBgoPed.DmpAlgBgoPed()
rdcAlgBT.SetConnector("Psd",DMPSW.WorkPath+"/share/Connector/Psd/EQM")
rdcAlgBT.SetConnector("Bgo",DMPSW.WorkPath+"/share/Connector/Bgo/EQM")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)
DMPSW.AlgMgr.Append(calBgoPed)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

