#! /usr/bin/python
'''
 *  $Id: JobOpt_CalPed_fromHex, 2015-03-07 17:05:47 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
#-------------------------------------------------------------------
    NOTE:   input data is scientific binary data
'''

#-------------------------------------------------------------------
import os
import glob
import DMPSW                    # Load DAMPE software
import libDmpHex2Root as Hex2Root
import libDmpCalPed as DmpCalPed

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.SetEventNumber(4000)     # default: -1
#DMPSW.Core.StartTime("2013-01-01 00:00:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.StopTime("2016-01-01 00:00:00")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off
DMPSW.Core.SetMode("EQM")

#DBase=DMPSW.WorkPath+"/run/BT"
#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.InputPath(DBase+"/sci")
#newestData=max(glob.iglob(DBase+"/sci/*.frd"),key=os.path.getctime)
DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141117_135210.frd")
#DMPSW.RootIOSvc.SetInputFile("./A2Data00_20141101_125310.frd")
#DMPSW.RootIOSvc.OutputPath(DMPSW.WorkPath+"/run/data/cal/ped")
DMPSW.RootIOSvc.SetWriteList("Event/Rdc")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = Hex2Root.DmpAlgHex2Root()
calPed = DmpCalPed.DmpAlgCalibrationPed()
#rdcAlgBT.SetConnector("Psd",DMPSW.WorkPath+"/share/Connector/Psd/EQM")
#rdcAlgBT.SetConnector("Bgo",DMPSW.WorkPath+"/share/Connector/Bgo/EQM")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)
DMPSW.AlgMgr.Append(calPed)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

